In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
df = pd.read_excel(r'Rent.xlsx')
df

area   rent
0   2000  31500
1   2100  35000
2   2500  41050
3   2250  36100
4   3000  52100
5   1900  32500
6   1500  20000
7   1850  24500
8   2700  48000
9   2100  31000
10  2150  34500
11  2100  32000
12  2100  34500
13  2510  40050
14  2250  34100
15  3100  51500
16  1800  30500
17  1550  21000
18  1800  25000
19  2700  47000
20  2110  31500
21  2100  33500
22  3500  70000
23  1200  20000
24  2800  50000
25  3100  53000
26  2750  48000
27  1800  25000
28  2200  31460
29  3100  51400
30  2100  33500
31  2100  35010
32  2500  41100
33  2250  35100
34  3000  52200
35  1900  32300
36  1500  20200
37  1850  24000
38  2700  47500
39  2100  31500
40  2150  34400
41  2100  32020
42  2100  34700
43  2510  40000
44  2250  35000
45  3100  51000
46  1800  30000
47  1550  21500
48  1800  25500
49  2700  47500
50  2110  31000
51  2100  33000
52  3500  70500
53  1200  20100
54  2800  51000
55  3100  54000
56  2750  48500
57  1800  25100
58  2200  31560
59  3100  51600

In [7]:
df.shape

(60, 2)

### Step 1: Apply Preprocessing Steps

In [10]:
df.isnull().sum()

area    0
rent    0
dtype: int64

### Step 2: Separate independent and dependent variable

In [17]:
x = df.drop('rent',axis=1)
x

area
0   2000
1   2100
2   2500
3   2250
4   3000
5   1900
6   1500
7   1850
8   2700
9   2100
10  2150
11  2100
12  2100
13  2510
14  2250
15  3100
16  1800
17  1550
18  1800
19  2700
20  2110
21  2100
22  3500
23  1200
24  2800
25  3100
26  2750
27  1800
28  2200
29  3100
30  2100
31  2100
32  2500
33  2250
34  3000
35  1900
36  1500
37  1850
38  2700
39  2100
40  2150
41  2100
42  2100
43  2510
44  2250
45  3100
46  1800
47  1550
48  1800
49  2700
50  2110
51  2100
52  3500
53  1200
54  2800
55  3100
56  2750
57  1800
58  2200
59  3100

In [23]:
y = df['rent']
y

0     31500
1     35000
2     41050
3     36100
4     52100
5     32500
6     20000
7     24500
8     48000
9     31000
10    34500
11    32000
12    34500
13    40050
14    34100
15    51500
16    30500
17    21000
18    25000
19    47000
20    31500
21    33500
22    70000
23    20000
24    50000
25    53000
26    48000
27    25000
28    31460
29    51400
30    33500
31    35010
32    41100
33    35100
34    52200
35    32300
36    20200
37    24000
38    47500
39    31500
40    34400
41    32020
42    34700
43    40000
44    35000
45    51000
46    30000
47    21500
48    25500
49    47500
50    31000
51    33000
52    70500
53    20100
54    51000
55    54000
56    48500
57    25100
58    31560
59    51600
Name: rent, dtype: int64

### Step 3: Splitting data into train and test

In [26]:
from sklearn.model_selection import train_test_split

In [28]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

### Step 4: Algorithm Implementation

In [31]:
from sklearn.linear_model import LinearRegression

In [35]:
LR = LinearRegression()
LR

LinearRegression()

### Step 5: Model Train

In [38]:
LR.fit(x_train, y_train)

LinearRegression()

### Step 6: Model Predict

In [43]:
y_pred = LR.predict(x_test)
y.36419_pred

array([31083.36419012, 28934.68187439, 20339.95261148, 54718.86966312,
       42041.64400032, 48272.82271593, 36455.06997943, 26785.99955866,
       33232.04650584, 26785.99955866, 26785.99955866, 33446.91473742])

In [45]:
y_test

0     31500
5     32500
36    20200
45    51000
13    40050
54    51000
33    35100
48    25500
12    34500
57    25100
46    30000
50    31000
Name: rent, dtype: int64

### Step 7: Error

In [48]:
error = y_test - y_pred
error

0      416.635810
5     3565.318126
36    -139.952611
45   -3718.869663
13   -1991.644000
54    2727.177284
33   -1355.069979
48   -1285.999559
12    1267.953494
57   -1685.999559
46    3214.000441
50   -2446.914737
Name: rent, dtype: float64

### Step 8: Check Score

#### Training Score

In [52]:
LR.score(x_train,y_train)

0.9508465043158032

#### Testing Score

In [55]:
LR.score(x_test,y_pred)

1.0

### Predicting Outside Dataset

In [58]:
LR.predict([[2050]])

C:\Users\jadem\AppData\Roaming\Python\Python311\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([32157.70534798])

In [60]:
LR.predict([[5020]])

C:\Users\jadem\AppData\Roaming\Python\Python311\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([95973.57012508])